#!/bin/bash

# -----------------------------------------------------------------------------
# STEP 2: LINK
#
# Softlinks the dotfiles where they belong.
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Atom
# -----------------------------------------------------------------------------

mkdir "${HOME}/.atom"
ln -s "${DOTFILES_ROOT}/.atom/config.cson" "${HOME}/.atom/config.cson"
ln -s "${DOTFILES_ROOT}/.atom/init.coffee" "${HOME}/.atom/init.coffee"
ln -s "${DOTFILES_ROOT}/.atom/keymap.cson" "${HOME}/.atom/keymap.cson"
ln -s "${DOTFILES_ROOT}/.atom/projects.cson" "${HOME}/.atom/projects.cson"
ln -s "${DOTFILES_ROOT}/.atom/snippets.cson" "${HOME}/.atom/snippets.cson"
ln -s "${DOTFILES_ROOT}/.atom/style.less" "${HOME}/.atom/style.less"

# -----------------------------------------------------------------------------
# Code
# -----------------------------------------------------------------------------

mkdir "${HOME}/Library/Application Support/Code/User"
ln -s "${DOTFILES_ROOT}/vscode/keybindings.json" "${HOME}/Library/Application Support/Code/User/keybindings.json"
ln -s "${DOTFILES_ROOT}/vscode/settings.json" "${HOME}/Library/Application Support/Code/User/settings.json"
ln -s "${DOTFILES_ROOT}/vscode/snippets" "${HOME}/Library/Application Support/Code/User/snippets"

# -----------------------------------------------------------------------------
# Git
# -----------------------------------------------------------------------------

ln -s "${DOTFILES_ROOT}/git/.gitconfig" "${HOME}/.gitconfig"
ln -s "${DOTFILES_ROOT}/git/.gitignore_global" "${HOME}/.gitignore_global"

# -----------------------------------------------------------------------------
# Command line bookmarks
# -----------------------------------------------------------------------------

mkdir "${HOME}/.bookmarks"
