#!/bin/bash

# -----------------------------------------------------------------------------
# STEP 2: LINK
#
# Softlinks the dotfiles where they belong.
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# Code
# -----------------------------------------------------------------------------

mkdir "${HOME}/Library/Application Support/Code/User"
ln -s "${DOTFILES_ROOT}/vscode/keybindings.json" "${HOME}/Library/Application Support/Code/User/keybindings.json"
ln -s "${DOTFILES_ROOT}/vscode/settings.json" "${HOME}/Library/Application Support/Code/User/settings.json"
ln -s "${DOTFILES_ROOT}/vscode/snippets" "${HOME}/Library/Application Support/Code/User/snippets"

# -----------------------------------------------------------------------------
# Git
# -----------------------------------------------------------------------------

ln -s "${DOTFILES_ROOT}/git/.gitconfig" "${HOME}/.gitconfig"
ln -s "${DOTFILES_ROOT}/git/.gitignore_global" "${HOME}/.gitignore_global"

# -----------------------------------------------------------------------------
# Command line bookmarks
# -----------------------------------------------------------------------------

mkdir "${HOME}/.bookmarks"
