#!/bin/bash

# -----------------------------------------------------------------------------
# UPDATE
#
# Launches updating commands for some of the package managers. Based on Lars
# Kappert's _Getting Started With Dotfiles_.
# -----------------------------------------------------------------------------

# App Store
printf "App Store:\n"
sudo softwareupdate --install --all

# Update Homebrew & packages
printf "\nUpdate Homebrew & packages:\n"
brew update
brew upgrade

# Update NPM & packages
printf "\nUpdate NPM & packages:\n"
npm install -g npm
npm update -g

# Update Ruby gems
printf "\nUpdate Ruby gems:\n"
gem update
