tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "autoconf"
brew "cowsay"
brew "fortune"
brew "fzf"
brew "mas"
brew "node"
brew "openssl"
brew "pkg-config"
brew "readline"
brew "postgresql"
brew "ruby-build"
brew "rbenv"
brew "tag"
brew "xz"
brew "yarn"
cask "appcleaner"
cask "backblaze"
cask "firefox"
cask "liteicon"
cask "netnewswire"
cask "sketch"
cask "visual-studio-code"
cask "whatsapp"
mas "1Password 7", id: 1333542190
mas "Adblock Plus", id: 1432731683
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "Lightroom", id: 1451544217
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "The Unarchiver", id: 425424353
mas "Todoist", id: 585829637
