#!/bin/bash

set -ueEo pipefail
IFS=$'\n\t'

echo "What's the path of your dotfiles folder?"
read DOTFILES_ROOT

if [[ "$DOTFILES_ROOT" == "" || ! $? ]]; then
  echo "[error] please provide a path"
  exit 1
fi

# Create a .dotfiles_local file in the home folder pointing to the selected
# path. The file will be read by the shell, so it can also contain local
# customizations that you don't want to add to the dotfiles repository.
dotfiles_local_path="${DOTFILES_ROOT}/environment/dotfiles_local"
if [[ ! -e "$dotfiles_local_path" ]]; then
  echo "#!/bin/bash" > "$dotfiles_local_path"
  echo "export DOTFILES_ROOT=\"${DOTFILES_ROOT}\"" >> "$dotfiles_local_path"
else
  echo "$dotfiles_local_path: File exists"
fi

# This file will be included by your git config and can be used to set local
# users, aliases and other configuration that you don't want to add to the
# dotfiles repository.
touch "${DOTFILES_ROOT}/environment/gitconfig_local"

# Create command line bookmarks folder
mkdir -p "${HOME}/.bookmarks"

# Link terminal profile from the dotfiles folder to the home folder
ln -s "${DOTFILES_ROOT}/environment/dotfiles_local" "${HOME}/.dotfiles_local"
ln -s "${DOTFILES_ROOT}/environment/gitconfig" "${HOME}/.gitconfig"
ln -s "${DOTFILES_ROOT}/environment/gitconfig_local" "${HOME}/.gitconfig_local"
ln -s "${DOTFILES_ROOT}/environment/gitignore_global" "${HOME}/.gitignore_global"
ln -s "${DOTFILES_ROOT}/environment/zprofile" "${HOME}/.zprofile"
ln -s "${DOTFILES_ROOT}/environment/zshrc" "${HOME}/.zshrc"

# Link nvim config
mkdir -p "${HOME}/.config/nvim"
ln -s "${DOTFILES_ROOT}/environment/init.lua" "${HOME}/.config/nvim/init.lua"

# Link ghostty config
mkdir -p "${HOME}/.config/ghostty"
ln -s "${DOTFILES_ROOT}/environment/ghostty" "${HOME}/.config/ghostty/config"

# Link lazygit config
mkdir -p "${HOME}/.config/lazygit"
ln -s "${DOTFILES_ROOT}/environment/lazygit.yml" "${HOME}/.config/lazygit/config.yml"

# Link helix config
mkdir -p "${HOME}/.config/helix"
ln -s "${DOTFILES_ROOT}/environment/helix.toml" "${HOME}/.config/helix/config.toml"

# Link VS Code config
mkdir -p "${HOME}/Library/Application Support/Code/User"
ln -s "${DOTFILES_ROOT}/vscode/keybindings.json" "${HOME}/Library/Application Support/Code/User/keybindings.json"
ln -s "${DOTFILES_ROOT}/vscode/settings.json" "${HOME}/Library/Application Support/Code/User/settings.json"
ln -s "${DOTFILES_ROOT}/vscode/snippets" "${HOME}/Library/Application Support/Code/User/"

# Link Zed config
mkdir -p "${HOME}/.config/zed"
ln -s "${DOTFILES_ROOT}/zed/keymap.json" "${HOME}/.config/zed/keymap.json"
ln -s "${DOTFILES_ROOT}/zed/settings.json" "${HOME}/.config/zed/settings.json"
ln -s "${DOTFILES_ROOT}/zed/tasks.json" "${HOME}/.config/zed/tasks.json"
ln -s "${DOTFILES_ROOT}/zed/snippets" "${HOME}/.config/zed/"
