#!/bin/bash

# -----------------------------------------------------------------------------
# INITIALIZE
#
# Sets up the dotfiles on the current machine. You'll first be prompted for
# the path of the dotfiles folder. The script adds file containing that path
# to your home folder, which will be referenced in the future. Afterwards
# the different configuration files will be softlinked.
# -----------------------------------------------------------------------------

echo "What's the path of your dotfiles folder?"
read dotfilesPath

if [[ $dotfilesPath != ""  && $? ]]
then
  # Create a .local_dotfiles file in the home folder pointing to the selected
  # path. The file will be read by the shell, so it can also contain local
  # customizations that you don't want to add to the dotfiles repository.
  echo "#!/bin/bash
  export DOTFILES_ROOT=\"${dotfilesPath}\"" > "${HOME}/.local_dotfiles"
  . "${HOME}/.local_dotfiles"

  # Link terminal profile from the dotfiles folder to the home folder
  echo "Linking .zshrc ..."
  ln -s "${DOTFILES_ROOT}/environment/.zshrc" "${HOME}/.zshrc"

  # Link vim configuration
  echo "Linking vim config ..."
  ln -s "${DOTFILES_ROOT}/environment/.vimrc" "${HOME}/.vimrc"

  # Link VS Code configuration
  echo "Linking VS Code configuration ..."
  mkdir -p "${HOME}/Library/Application Support/Code/User"
  ln -s "${DOTFILES_ROOT}/vscode/keybindings.json" "${HOME}/Library/Application Support/Code/User/keybindings.json"
  ln -s "${DOTFILES_ROOT}/vscode/settings.json" "${HOME}/Library/Application Support/Code/User/settings.json"
  ln -s "${DOTFILES_ROOT}/vscode/snippets" "${HOME}/Library/Application Support/Code/User/snippets"

  # Link global git configuration
  echo "Linking global Git configuration ..."
  ln -s "${DOTFILES_ROOT}/git/.gitconfig" "${HOME}/.gitconfig"
  ln -s "${DOTFILES_ROOT}/git/.gitignore_global" "${HOME}/.gitignore_global"

  # Create command line bookmarks folder
  mkdir "${HOME}/.bookmarks"
else
  echo "Please provide a path."
fi
