#!/bin/bash

set +e

while read -r extension
do
  if [[ "$extension" =~ \#.+ ]]
  then
    echo "Skipping ${extension}"
  else
    code --install-extension "$extension"
  fi
done < "$DOTFILES_ROOT/setup/Codefile"

set -e
