#!/bin/bash

# -----------------------------------------------------------------------------
# INSTALL
#
# Functions for setting up command line tools, package managers and other
# software.
#
# Usage: Run `. install` to get access to the functions below. 
# -----------------------------------------------------------------------------

function installZsh {
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  
  # Plugins
  git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
}

function installHomebrew {
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  brew tap "homebrew/bundle"
}

function installCodeExtensions {
  set +e

  while read -r extension
  do
    if [[ "$extension" =~ \#.+ ]]
    then
      echo "Skipping ${extension}"
    else
      code --install-extension "$extension"
    fi
  done < "$DOTFILES_ROOT/setup/Codefile"

  set -e
}
